### ISSUE TITLE
Intégration Page Accueil #3

### ISSUE THREAD

**Issue by meach-kaddour** [meach-kaddour/Covitest-kaddour#2]
- Convertion de design graphique de la page d'accueil en un code HTML CSS compressé et Compatible avec tous les navigateur en utilisant NPM, SASS.

- Analysez bien le [Design](https://github.com/Youcode-team/C2N3_C3N3/tree/master/Design)

- Intégrez votre code html en respectant la structure que vous venez d’imaginer

- Pensez bien à votre stratégie de découpage.

- Nommez vos blocs de façon sémantique en utilisant le concept BEM

- Incluez un [reset ](https://necolas.github.io/normalize.css/) css dans le header de votre page html.

- [x] Intégration section` Hero Header `contenant Menu , Warning Info, Illustration et son texte et `Boutto`n Test
- [x] Intégration section Symptômes 
- [x] Intégration Recommandations officielles
- [x]  Intégration section` Hero Footer` contenant la section Test et le `footer`

Notez Bien :

Cette page peut être élaborer qu'avec du Flexbox et même sans média queries.
💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯

**Comment by meach-kaddour** [comment]
page fini il juste manque le fixage de navbar

**Comment by youssefbm** [comment]
Il te reste des petits retouches que tu peux faire vers la fin du brief. Mais généralement, bon travail.
